### ISSUE TITLE
Crash at epoch 200

### ISSUE THREAD

**Issue by JordanMicahBennett** [ConorLazarou/PokeGAN#4]
Thanks for the quick answer to the prior issue Lazarou. Marvelous code. 

Any chance that you have the pre-trained model somewhere?

Epoch 199 results on py36 on my machine:
![image](https://user-images.githubusercontent.com/3666405/111708518-ff111d80-8813-11eb-97fb-89cf5e601174.png)

Within 200 epochs, I saw proper results forming. 

However, got a crash after that time.

![image](https://user-images.githubusercontent.com/3666405/111708738-68912c00-8814-11eb-8dc9-123f410bfb69.png)

Wondering if that crash happened because I tried to invoke gpu to do training on a separate task  which uses tensorflow/gpu compute on my machine.

**Comment by JordanMicahBennett** [comment]
I may be missing something, but I have been trying to load the saved checkpoint at epoch 199 or 100 before the crash above. I see various ways, I can't seem to find loading strategy for loading the models saved for the generator.

Again, thanks for your marvelous code. Going to try to find a way to customize the nn.Module that the AEGAN class processes to load saved model.

**Comment by JordanMicahBennett** [comment]
Update!!!!!

Epoch 1 result after loading pretrained checkpoint for generator:

![image](https://user-images.githubusercontent.com/3666405/111712067-ee17da80-881a-11eb-83db-dfdc02dceae6.png)

2 lines of code added to perform the above, from torch documents (Only add 2 lines below if checkpoint exists, no need to define gan, as this was already done by Conor author):

![image](https://user-images.githubusercontent.com/3666405/111712042-e48e7280-881a-11eb-91f3-6568fd8957a0.png)

I managed to load the checkpoint for the pre-trained generator, and seemed to successfully get gen.0000.png to look like the results of epoch 200 before the prior crash above, **instead of the coloured squares attained from a freshly starting gan**!!!!!

All I did was to add 2 lines, for changing the state of the gan from the gan = AEGAN statement, such that the new state is the state of the saved checkpoint that was fortunately saved every 50 epochs prior.

////////////////////////////////
Warning!!!!!
I notice that starting separate tensorflow/gpu enabled commands will definitely crash the existing training.
Turns out my gpu is quite limited at 6gb/gtx 1060.

So now epoch

Take care. 

I will report resutls after 1000 epochs.

**Comment by ConorLazarou** [comment]
Looking good! And yeah, it sounds like you're maxing out your GPU there. I've never seen the error you posted, but but running out of VRAM seems like the culprit.

I've uploaded the generator weights as requested 🙂

**Comment by JordanMicahBennett** [comment]
> Looking good! And yeah, it sounds like you're maxing out your GPU there. I've never seen the error you posted, but but running out of VRAM seems like the culprit.
> 
> I've uploaded the generator weights as requested 🙂

Many thanks Conor !!!!!
