### ISSUE TITLE
20000 epochs??!?!?

### ISSUE THREAD

**Issue by JordanMicahBennett** [ConorLazarou/PokeGAN#5]
Thanks for the marvelous code again.
Did you really train  that wonderful AEGAN architecture for 20k epochs?!?!

I asked, because I saw 20k in the epoch variable in the default code you nicely provided:

![image](https://user-images.githubusercontent.com/3666405/112016988-337a2780-8afb-11eb-9376-1601090661ad.png)

My gtx 1060 is crying at the moment, after 2375 epochs.

**Comment by ConorLazarou** [comment]
Yup! It took about a week on my GTX 2080. Canadian winters are cold, but my GPU kept my office nice and toasty that week.

**Comment by JordanMicahBennett** [comment]
> Yup! It took about a week on my GTX 2080. Canadian winters are cold, but my GPU kept my office nice and toasty that week.

Oh my!
No wonder my gtx 1060 only completed roughly 4000 epochs after a week!!
Much appreciated!
